DATA_PATH = "dataset/"
TEST_DATA_PATTERN = "_test_data.xlsx"
NORMAL_DATA_FIRST_SIX = "M_train_data.xlsx"
NORMAL_DATA_SEVENTH_NINE = "U_train_data.xlsx"
MULTI_VAR_COLUMNS = ['Variable 1','Variable 2','Variable 3','Variable 4','Variable 5', 'Variable 6', 'Variable 7', 'Variable 8','Variable 9','Variable 10','Variable 11','Variable 12','Variable 13','Variable 14','Variable 15','Variable 16','Variable 17','Variable 18','Variable 19','Variable 20','Variable 21','Variable 22','Variable 23','Variable 24','Variable 25','Variable 26','Variable 27']
SINGLE_VAR_COLUMN = ["Data"]
WINDOW_SIZE = 500  
STEP_SIZE = 100     
stage = "generate"
ALPHA = 0.2       
BETA = 0.1         
num_samples=1 # Do not need to repeat as we set temperature = 1
# enhancement strategies
POSITIVE_SAMPLE_NUMBER = 1
NEGATIVE_SAMPLE_NUMBER = 3
RAG_NUMBER= 0
MODEL_CONFIG = {
    "deepseek-chat": {"api_key": "", "endpoint": "https://api.deepseek.com/v1"}, 
    "qwen3-235b-a22b":{"api_key": "", "endpoint": "https://dashscope.aliyuncs.com/compatible-mode/v1"}
}
# The maximum and minimum values for each variable, used for preprocessing, are generated by get_min_max_values.py. Due to data confidentiality, we use all zeros here as a placeholder.
COLUMNS_MIN_MAX_VALUES={
    "Variable 1": {
        "min": 0,
        "max": 0
    },
    "Variable 2": {
        "min": 0,
        "max": 0
    },
    "Variable 3": {
        "min": 0,
        "max": 0
    },
    "Variable 4": {
        "min": 0,
        "max": 0
    },
    "Variable 5": {
        "min": 0,
        "max": 0
    },
    "Variable 6": {
        "min": 0,
        "max": 0
    },
    "Variable 7": {
        "min": 0,
        "max": 0
    },
    "Variable 8": {
        "min": 0,
        "max": 0
    },
    "Variable 9": {
        "min": 0,
        "max": 0
    },
    "Variable 10": {
        "min": 0,
        "max": 0
    },
    "Variable 11": {
        "min": 0,
        "max": 0
    },
    "Variable 12": {
        "min": 0,
        "max": 0
    },
    "Variable 13": {
        "min": 0,
        "max": 0
    },
    "Variable 14": {
        "min": 0,
        "max": 0
    },
    "Variable 15": {
        "min": 0,
        "max": 0
    },
    "Variable 16": {
        "min": 0,
        "max": 0
    },
    "Variable 17": {
        "min": 0,
        "max": 0
    },
    "Variable 18": {
        "min": 0,
        "max": 0
    },
    "Variable 19": {
        "min": 0,
        "max": 0
    },
    "Variable 20": {
        "min": 0,
        "max": 0
    },
    "Variable 21": {
        "min": 0,
        "max": 0
    },
    "Variable 22": {
        "min": 0,
        "max": 0
    },
    "Variable 23": {
        "min": 0,
        "max": 0
    },
    "Variable 24": {
        "min": 0,
        "max": 0
    },
    "Variable 25": {
        "min": 0,
        "max": 0
    },
    "Variable 26": {
        "min": 0,
        "max": 0
    },
    "Variable 27": {
        "min": 0,
        "max": 0
    }
}